name: IMGSender
version: 0.4
main: fr.skyost.imgsender.IMGSender
author: Skyost
website: http://www.skyost.eu
commands:
 img:
  description: Send an image.
  usage: /img [url] [size] [char] [text] [player].
  permission: img.send
permissions:
  img.send:
   default: true
   description: Allow you to send an image.
