name: IMGSender
version: 1.0
main: fr.skyost.imgsender.IMGSender
author: Skyost
website: http://www.skyost.eu
commands:
 img:
  aliases: [image, pic, picture]
  description: Main command to send an image.
  usage: /img [url] [size] [char] [text] [player].
 img-item:
  aliases: [image-item, pic-item, picture-item]
  description: Main command to apply an image to an item.
  usage: /img-item [url] [size] [char] [text].
permissions:
 img.*:
  description: Give you all IMGSender permissions.
  children:
   img.broadcast.send: true
   img.broadcast.receive: true
   img.private.send: true
   img.private.receive: true
   img.item: true
 img.broadcast.*:
  description: Give you all "broadcast" permissions.
  children:
   img.broadcast.send: true
   img.broadcast.receive: true
 img.private.*:
  description: Give you all "private" permissions.
  children:
   img.private.send: true
   img.private.receive: true
 img.private.send:
  default: true
  description: Allows you to send an image to a single player.
 img.broadcast.send:
  default: true
  description: Allows you to broadcast an image.
 img.private.receive:
  default: true
  description: Allows you to receive an image sent privately.
 img.broadcast.receive:
  default: true
  description: Allows you to receive a broadcasted image.
 img.item:
  default: true
  description: Allows you to apply an image to an item.
 